// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwTXk5yLq2G-YX2sdFu2Rk6VyclfFVr0',
    appId: '1:926704482300:web:51019e15c21c57e24aa479',
    messagingSenderId: '926704482300',
    projectId: 'jeevdhara',
    authDomain: 'jeevdhara.firebaseapp.com',
    storageBucket: 'jeevdhara.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSGT-ZC1IxtZexZmpaXUL14_6VAIs7K0o',
    appId: '1:926704482300:android:c23ab92dce1364244aa479',
    messagingSenderId: '926704482300',
    projectId: 'jeevdhara',
    storageBucket: 'jeevdhara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBq-owMIamhQtnPJqoLM5QiXHQ9F-7qO8',
    appId: '1:926704482300:ios:e5d847cfe74b06b44aa479',
    messagingSenderId: '926704482300',
    projectId: 'jeevdhara',
    storageBucket: 'jeevdhara.firebasestorage.app',
    iosBundleId: 'com.example.jeevdhara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBq-owMIamhQtnPJqoLM5QiXHQ9F-7qO8',
    appId: '1:926704482300:ios:e5d847cfe74b06b44aa479',
    messagingSenderId: '926704482300',
    projectId: 'jeevdhara',
    storageBucket: 'jeevdhara.firebasestorage.app',
    iosBundleId: 'com.example.jeevdhara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkwTXk5yLq2G-YX2sdFu2Rk6VyclfFVr0',
    appId: '1:926704482300:web:d1eeec431583f9644aa479',
    messagingSenderId: '926704482300',
    projectId: 'jeevdhara',
    authDomain: 'jeevdhara.firebaseapp.com',
    storageBucket: 'jeevdhara.firebasestorage.app',
  );
}
